---
title: "Last Lab"
author: "Hugo Sparrman"
format: html
editor: visual
---

https://github.com/kennethsprak/Final-Lab-Hugo-Sparrman

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(vroom)
library(here)
i_am("Final_lab.qmd")
```

### Question 3
```{r, message=FALSE}
stars <- vroom("Data/bt-data-systems.csv",delim = ":",locale = locale(decimal_mark = ","))

if (nrow(stars) == 1052 & ncol(stars)==8) {
  print("The file loading was sucessful")
  } else {
    print("The file loading was unsucessful")
}

  
```

### Question 4
```{r}
test1<-stars|>
  summarise("Number of observations" = nrow(stars),
            "Number of variables" = ncol(stars),
            "Missing values" = across(everything(), ~sum(is.na(.))))

```

### Question 5

```{r}
stars|>
  drop_na()|>
  ggplot(aes(x = `Equivalent Temperature`,y =`Star Radius`)) +
  geom_point()+
  labs(x = "Temperature", y = "Radius")
```

### Question 6 

```{r}
sum_stats<-stars|>
  summarise("Size of biggest star" = max(`star mass`, na.rm = T),
            "Size of smallest star" = min(`star mass`, na.rm = T),
            "max_radius" = max(`Star Radius`, na.rm = T),
            "min radius" =  min(`Star Radius`, na.rm = T),
            "Hottest star" = max(`Equivalent Temperature`,na.rm = T),
            "Coldest star" = min(`Equivalent Temperature`,na.rm = T),
            "Brightest star" = max(`STAR LUMINOSITY`, na.rm = T),
            "Coldest star" = min(`Equivalent Temperature`,na.rm = T))

knitr::kable(sum_stats)


```


